#!/usr/bin/env bash
#a script the configures an Ubuntu Server
#local host resolves to 127.0.0.2
#facebook.com resolves to 8.8.8.8

cp /etc/hosts ~host.new
echo "127.0.0.2 localhost" >> ~/hosts.new
echo "8.8.8.8   facebook.com" >> ~hosts.new
cp -f ~hosts.new /etc/hosts
